# Generated by Django 5.2.10 on 2026-06-02 12:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('texto', models.CharField(max_length=300)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('hecha', models.BooleanField(default=False)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea diaria',
                'verbose_name_plural': 'Tareas diarias',
                'ordering': ['hecha', 'hora', 'orden', 'created_at'],
            },
        ),
    ]
