# Generated by Django 5.2.10 on 2026-06-01 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoFuturo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('concepto', models.CharField(blank=True, help_text='Ej: Alquiler, Venta, Comisión, Otro', max_length=120, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Opcional al agendar. Se confirma al marcar como cobrado.', max_digits=14, verbose_name='Monto')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de cobro estimada')),
                ('destino', models.CharField(choices=[('control_ingresos', 'Control de Ingresos'), ('ingresos_personales', 'Ingresos Personales')], default='control_ingresos', help_text='Control de Ingresos = ingreso de la concesionaria · Ingresos Personales = ingreso del usuario que cobra.', max_length=20, verbose_name='Destino al cobrar')),
                ('forma_cobro', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20, verbose_name='Forma de cobro')),
                ('es_recurrente_mensual', models.BooleanField(default=False, help_text='Si está activo, al cobrarse se agenda automáticamente el del mes siguiente.', verbose_name='Ingreso mensual recurrente')),
                ('recurrente_hasta', models.DateField(blank=True, help_text='Solo si es recurrente: hasta qué fecha se sigue agendando. Vacío = sin límite.', null=True, verbose_name='Recurrente hasta')),
                ('cobrado', models.BooleanField(default=False)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ingreso_mensual_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ingreso_personal_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cobrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_futuros_cobrados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_futuros_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso futuro',
                'verbose_name_plural': 'Agenda de Ingresos',
                'ordering': ['cobrado', 'fecha_vencimiento', '-id'],
            },
        ),
    ]
