# Generated by Django 6.0.2 on 2026-04-15 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_texto', models.CharField(blank=True, help_text='Guardamos el nombre por si se borra el usuario', max_length=150)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('login_fallido', 'Login fallido')], max_length=20)),
                ('modelo', models.CharField(blank=True, help_text='Tabla afectada (ej: Vehiculo, Venta, Pago)', max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('datos_antes', models.JSONField(blank=True, null=True)),
                ('datos_despues', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de actividad',
                'verbose_name_plural': 'Logs de actividad',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='auditoria_l_fecha_dcc1e2_idx'), models.Index(fields=['usuario', '-fecha'], name='auditoria_l_usuario_e92c4d_idx'), models.Index(fields=['modelo', '-fecha'], name='auditoria_l_modelo_214c47_idx')],
            },
        ),
    ]
