# Generated by Django 4.2.27 on 2026-01-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('vtv', 'Turno VTV'), ('autopartes', 'Turno Grabado de Autopartes')], max_length=50, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='vehiculos.vehiculo')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
