# Generated by Django 6.0.2 on 2026-04-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0015_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Agencia / Comprador')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('revertida', 'Revertida')], default='pendiente', max_length=20)),
                ('precio_reventa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comision', models.DecimalField(decimal_places=2, default=0, help_text='Comision o ganancia de la operacion', max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_reventa', models.DateField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateField(blank=True, null=True)),
                ('vehiculo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reventa', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Reventa',
                'verbose_name_plural': 'Reventas',
                'ordering': ['-fecha_reventa'],
            },
        ),
    ]
