# Generated by Django 6.0.2 on 2026-04-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reventa', '0002_cuentarevendedor_movimientorevendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reventa',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reventas', to='reventa.cuentarevendedor'),
        ),
    ]
