# Generated by Django 6.0.2 on 2026-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reventa', '0003_reventa_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reventa',
            name='documentacion_entregada',
            field=models.TextField(blank=True, help_text='Detalle de documentacion entregada con el vehiculo', null=True, verbose_name='Documentacion entregada'),
        ),
    ]
