# Generated by Django 5.2.10 on 2026-06-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reventa', '0005_reventa_enviar_a_gestoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='reventa',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra (el revendedor la compra → contrae deuda)'), ('consignacion', 'Consignación (se la lleva en consignación → sin deuda)')], default='compra', max_length=20, verbose_name='Tipo de reventa'),
        ),
    ]
