# Generated by Django 5.2.10 on 2026-07-28 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reventa', '0006_reventa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanReventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='reventa.cuentarevendedor')),
                ('reventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='reventa.reventa')),
            ],
            options={
                'verbose_name': 'Plan de pagos (reventa)',
                'verbose_name_plural': 'Planes de pagos (reventa)',
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuotaReventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuota_reventa', to='reventa.movimientorevendedor')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='reventa.planreventa')),
            ],
            options={
                'verbose_name': 'Cuota (reventa)',
                'verbose_name_plural': 'Cuotas (reventa)',
                'ordering': ['numero', 'vencimiento'],
            },
        ),
    ]
