# Generated by Django 5.2.10 on 2026-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financiera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de fantasía')),
                ('cuit', models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT')),
                ('contacto', models.CharField(blank=True, max_length=120, null=True, verbose_name='Persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('notas', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Desmarcá para ocultarla de la lista al marcar ventas financiadas.')),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Financiera',
                'verbose_name_plural': 'Financieras',
                'ordering': ['nombre'],
            },
        ),
    ]
