# Generated by Django 5.2.10 on 2026-01-28 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_remove_fichavehicular_chasis_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vehiculo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='vehiculos.vehiculo'),
        ),
    ]
