# Generated by Django 6.0.2 on 2026-02-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('revertida', 'Revertida')], default='pendiente', max_length=20),
        ),
    ]
