# Generated by Django 5.2.10 on 2026-06-25 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_vendido_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_comisiones', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cuenta de vendedor (comisiones)',
                'verbose_name_plural': 'Cuentas de vendedores (comisiones)',
                'ordering': ['vendedor__first_name', 'vendedor__username'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comision', 'Comisión generada'), ('pago', 'Pago al vendedor')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ventas.cuentavendedor')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_comision', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Movimiento de comisión',
                'verbose_name_plural': 'Movimientos de comisión',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
