# Generated by Django 5.2.10 on 2026-07-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiacion', '0001_initial'),
        ('ventas', '0005_cuentavendedor_movimientocomision'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='financiado',
            field=models.BooleanField(default=False, verbose_name='Financiado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='financiera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='financiacion.financiera', verbose_name='Financiera'),
        ),
    ]
