# Generated by Django 5.2.10 on 2026-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_financiado_venta_financiera'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_financiado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto financiado'),
        ),
    ]
