# Generated by Django 4.2.27 on 2026-01-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('transferido', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('finalizada', 'Finalizada')], default='vigente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('formulario_08', models.BooleanField(default=False)),
                ('titulo', models.BooleanField(default=False)),
                ('cedula', models.BooleanField(default=False)),
                ('informe_dominio', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones internas de la gestoría')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestoria', to='ventas.venta')),
            ],
        ),
    ]
