# Generated by Django 6.0.2 on 2026-04-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('gestoria', '0001_initial'),
        ('vehiculos', '0012_fichavehicular_gnc_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestoria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='gestoria',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculos.vehiculo'),
        ),
    ]
