# Generated by Django 5.2.10 on 2026-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoria', '0003_gestoria_cliente_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestoria',
            name='pago_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Pago cliente'),
        ),
        migrations.AddField(
            model_name='gestoria',
            name='pago_concesionaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Pago concesionaria'),
        ),
        migrations.AddField(
            model_name='gestoria',
            name='pago_escribania',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Pago escribanía'),
        ),
    ]
