# Generated by Django 5.2.10 on 2026-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestoria', '0004_gestoria_pago_cliente_gestoria_pago_concesionaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestoria',
            name='pago_concesionaria_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago concesionaria'),
        ),
        migrations.AddField(
            model_name='gestoria',
            name='pago_concesionaria_gestionado',
            field=models.BooleanField(default=False, verbose_name='Pago concesionaria gestionado'),
        ),
    ]
