# Generated by Django 5.2.10 on 2026-06-10 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0014_cuentacorriente_doc_entregada_and_more'),
        ('gestoria', '0005_gestoria_pago_concesionaria_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestoria',
            name='movimiento_transferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cuentas.movimientocuenta', verbose_name='Gasto de transferencia en cuenta'),
        ),
    ]
