# Generated by Django 5.2.10 on 2026-06-02 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_prospecto_origen_web_notificacion_vehiculo_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram'), ('messenger', 'Messenger')], max_length=20)),
                ('contacto_id', models.CharField(max_length=120)),
                ('nombre', models.CharField(blank=True, default='', max_length=150)),
                ('foto_url', models.URLField(blank=True, default='')),
                ('ultimo_texto', models.TextField(blank=True, default='')),
                ('ultima_fecha', models.DateTimeField(blank=True, null=True)),
                ('no_leido', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-ultima_fecha', '-id'],
                'unique_together': {('plataforma', 'contacto_id')},
            },
        ),
        migrations.CreateModel(
            name='LeadMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook')], default='facebook', max_length=20)),
                ('leadgen_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('form_id', models.CharField(blank=True, default='', max_length=120)),
                ('nombre', models.CharField(blank=True, default='', max_length=150)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('prospecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_meta', to='crm.prospecto')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrante', models.BooleanField(default=True)),
                ('texto', models.TextField(blank=True, default='')),
                ('mid', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='marketing.conversacionmeta')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
