# Generated by Django 6.0.2 on 2026-04-06 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('es_fijo', models.BooleanField(default=False, help_text='Indica si es un gasto fijo mensual (alquiler, sueldos, etc.)')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GastoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('unidad', models.CharField(choices=[('HA', 'Hamichetti'), ('VA', 'Vamichetti'), ('ambas', 'Ambas')], default='ambas', max_length=5)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos_mensuales.categoriagasto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto mensual',
                'verbose_name_plural': 'Gastos mensuales',
                'ordering': ['-anio', '-mes', 'categoria__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ResumenGastosMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('total_fijos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_variables', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
