# Generated by Django 5.2.10 on 2026-06-01 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_mensuales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Ej: Venta, Comisión, Alquiler cobrado, Otro', max_length=150, verbose_name='Concepto')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('unidad', models.CharField(choices=[('HA', 'Hamichetti'), ('VA', 'Vamichetti'), ('ambas', 'Ambas')], default='ambas', max_length=5)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso mensual',
                'verbose_name_plural': 'Ingresos mensuales',
                'ordering': ['-anio', '-mes', 'concepto'],
            },
        ),
    ]
