# Generated by Django 5.2.10 on 2026-05-28 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas_internas', '0001_initial'),
        ('gastos_mensuales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoFuturo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('destino', models.CharField(choices=[('cuentas_internas', 'Cuentas Internas'), ('control_gastos', 'Control de Gastos')], default='control_gastos', max_length=20, verbose_name='Destino al marcar pagado')),
                ('forma_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('otro', 'Otro')], help_text='Cargado al momento de marcar como pagado.', max_length=20, verbose_name='Forma de pago')),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('gasto_mensual_id', models.PositiveIntegerField(blank=True, null=True)),
                ('movimiento_interno_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Tipo de pago (alquiler, sueldos, servicios, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_futuros', to='gastos_mensuales.categoriagasto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_futuros_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_interna', models.ForeignKey(blank=True, help_text='Cuenta interna destino (solo si destino = Cuentas Internas).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_futuros', to='cuentas_internas.cuentainterna')),
            ],
            options={
                'verbose_name': 'Pago futuro',
                'verbose_name_plural': 'Agenda de pagos',
                'ordering': ['pagado', 'fecha_vencimiento', '-id'],
            },
        ),
    ]
