# Generated by Django 5.2.10 on 2026-05-28 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _migrar_destinos(apps, schema_editor):
    # Renombrar control_gastos -> gastos_personales para registros existentes.
    PagoFuturo = apps.get_model('agenda_pagos', 'PagoFuturo')
    PagoFuturo.objects.filter(destino='control_gastos').update(destino='gastos_personales')


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_migrar_destinos, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pagofuturo',
            name='gasto_mensual_id',
        ),
        migrations.AddField(
            model_name='pagofuturo',
            name='gasto_personal_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagofuturo',
            name='pagado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que marcó el pago como pagado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_futuros_pagados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagofuturo',
            name='destino',
            field=models.CharField(choices=[('cuentas_internas', 'Cuentas Internas'), ('gastos_personales', 'Gastos Personales')], default='gastos_personales', max_length=20, verbose_name='Destino al marcar pagado'),
        ),
    ]
