# Generated by Django 5.2.10 on 2026-05-28 21:29

import django.db.models.deletion
from django.db import migrations, models


def _migrar_destinos(apps, schema_editor):
    # Cualquier destino legacy 'cuentas_internas' lo mapeamos a 'control_gastos'.
    PagoFuturo = apps.get_model('agenda_pagos', 'PagoFuturo')
    PagoFuturo.objects.filter(destino='cuentas_internas').update(destino='control_gastos')


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_pagos', '0002_remove_pagofuturo_gasto_mensual_id_and_more'),
        ('gastos_mensuales', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_migrar_destinos, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='pagofuturo',
            name='cuenta_interna',
        ),
        migrations.RemoveField(
            model_name='pagofuturo',
            name='movimiento_interno_id',
        ),
        migrations.AddField(
            model_name='pagofuturo',
            name='gasto_mensual_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagofuturo',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Tipo de pago (alquiler, sueldos, celular, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_futuros', to='gastos_mensuales.categoriagasto'),
        ),
        migrations.AlterField(
            model_name='pagofuturo',
            name='destino',
            field=models.CharField(choices=[('control_gastos', 'Control de Gastos'), ('gastos_personales', 'Gastos Personales')], default='control_gastos', help_text='Control de Gastos = gasto de la concesionaria · Gastos Personales = gasto del usuario que paga.', max_length=20, verbose_name='Destino al marcar pagado'),
        ),
    ]
