# Generated by Django 5.2.10 on 2026-05-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_pagos', '0003_remove_pagofuturo_cuenta_interna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofuturo',
            name='es_recurrente_mensual',
            field=models.BooleanField(default=False, help_text='Si está activo, al marcarse como pagado se crea automáticamente el del mes siguiente.', verbose_name='Pago mensual recurrente'),
        ),
    ]
