# Generated by Django 5.2.10 on 2026-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_pagos', '0004_pagofuturo_es_recurrente_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagofuturo',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Opcional al agendar. Se pregunta al marcar como pagado.', max_digits=14, verbose_name='Monto'),
        ),
    ]
