# Generated by Django 5.2.10 on 2026-06-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_pagos', '0005_alter_pagofuturo_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagofuturo',
            name='recurrente_hasta',
            field=models.DateField(blank=True, help_text='Solo si es recurrente mensual: hasta qué fecha se sigue agendando (ej: fin de un crédito). Vacío = sin fecha de término.', null=True, verbose_name='Recurrente hasta'),
        ),
    ]
