# Generated by Django 5.2.10 on 2026-06-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_pagos', '0006_pagofuturo_recurrente_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagofuturo',
            name='destino',
            field=models.CharField(choices=[('control_gastos', 'Gastos Concesionario'), ('gastos_personales', 'Gastos Personales')], default='control_gastos', help_text='Gastos Concesionario = gasto de la concesionaria · Gastos Personales = gasto del usuario que paga.', max_length=20, verbose_name='Destino al marcar pagado'),
        ),
    ]
