# Generated by Django 5.2.10 on 2026-05-27 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_personales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto personal',
                'verbose_name_plural': 'Gastos personales',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
