# Generated by Django 5.2.10 on 2026-05-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_mensuales', '0001_initial'),
        ('gastos_personales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastopersonal',
            options={'ordering': ['-anio', '-mes', 'categoria__nombre'], 'verbose_name': 'Gasto personal', 'verbose_name_plural': 'Gastos personales'},
        ),
        migrations.RemoveField(
            model_name='gastopersonal',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='gastopersonal',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='gastopersonal',
            name='notas',
        ),
        migrations.AddField(
            model_name='gastopersonal',
            name='anio',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='gastopersonal',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gastopersonal',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gastopersonal',
            name='mes',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gastopersonal',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gastopersonal',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gastopersonal',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_personales', to='gastos_mensuales.categoriagasto'),
        ),
        migrations.AlterField(
            model_name='gastopersonal',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
