# Generated by Django 5.2.10 on 2026-06-01 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_personales', '0002_alter_gastopersonal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Ej: Sueldo, Venta, Alquiler cobrado, Otro', max_length=150, verbose_name='Concepto')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes', models.PositiveSmallIntegerField(default=1)),
                ('anio', models.PositiveIntegerField(default=2026)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_personales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso personal',
                'verbose_name_plural': 'Ingresos personales',
                'ordering': ['-anio', '-mes', 'concepto'],
            },
        ),
    ]
