# Generated by Django 5.2.10 on 2026-06-01 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_internas', '0003_remove_alquiler_propietario_and_more'),
        ('gastos_personales', '0003_ingresopersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresopersonal',
            name='pago_alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_personales', to='cuentas_internas.pagoalquiler'),
        ),
    ]
