# Generated by Django 4.2.27 on 2026-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('dominio', models.CharField(max_length=10, unique=True)),
                ('anio', models.PositiveIntegerField()),
                ('kilometros', models.PositiveIntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('stock', 'En stock'), ('vendido', 'Vendido')], default='stock', max_length=10)),
            ],
        ),
    ]
