# Generated by Django 5.2.10 on 2026-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_recordatoriodashboard_delete_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(default='Hugo', max_length=100, verbose_name='Titular')),
                ('banco', models.CharField(max_length=120, verbose_name='Banco')),
                ('numero_cuenta', models.CharField(blank=True, max_length=80, verbose_name='Número de cuenta')),
                ('cbu', models.CharField(blank=True, max_length=40, verbose_name='CBU')),
                ('alias', models.CharField(blank=True, max_length=80, verbose_name='Alias')),
                ('titular_cuenta', models.CharField(blank=True, max_length=140, verbose_name='Titular de la cuenta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'ordering': ['titular', 'banco'],
            },
        ),
    ]
