# Generated by Django 5.2.10 on 2026-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_cuentabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='sucursal',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sucursal'),
        ),
    ]
