# Generated by Django 6.0.2 on 2026-04-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0017_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/fotos/', verbose_name='Foto')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('es_portada', models.BooleanField(default=False, verbose_name='Foto de portada')),
                ('subida', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Foto de vehículo',
                'verbose_name_plural': 'Fotos de vehículos',
                'ordering': ['orden', '-subida'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('mercadolibre', 'MercadoLibre'), ('facebook', 'Facebook Marketplace'), ('instagram', 'Instagram'), ('web', 'Página web')], max_length=20)),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['plataforma'],
                'unique_together': {('vehiculo', 'plataforma')},
            },
        ),
    ]
