# Generated by Django 4.2.27 on 2026-01-02 12:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de factura / comprobante', max_length=50)),
                ('fecha', models.DateField(help_text='Fecha de la factura')),
                ('monto_neto', models.DecimalField(blank=True, decimal_places=2, help_text='Monto neto sin IVA', max_digits=14, null=True)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Porcentaje de IVA aplicado', max_digits=5)),
                ('monto_iva', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de IVA calculado', max_digits=14, null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total facturado (neto + IVA)', max_digits=14)),
                ('estado', models.CharField(choices=[('valida', 'Válida'), ('anulada', 'Anulada')], default='valida', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Factura registrada',
                'verbose_name_plural': 'Facturas registradas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['numero'], name='facturacion_numero_213750_idx'), models.Index(fields=['fecha'], name='facturacion_fecha_64837f_idx')],
            },
        ),
    ]
