# Generated by Django 6.0.2 on 2026-04-07 11:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numero de factura de compra', max_length=50)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateField()),
                ('monto_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5)),
                ('monto_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total (neto + IVA)', max_digits=14)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compra registrada',
                'verbose_name_plural': 'Compras registradas',
                'ordering': ['-fecha'],
            },
        ),
    ]
