# Generated by Django 6.0.2 on 2026-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_compraregistrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraregistrada',
            name='otros_impuestos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tasas, percepciones, imp. internos, etc.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='compraregistrada',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto total (neto + IVA + otros impuestos)', max_digits=14),
        ),
    ]
