# Generated by Django 5.2.10 on 2026-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_compraregistrada_otros_impuestos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaregistrada',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Detalle de la factura (servicio, concepto, etc.)', max_length=200, null=True),
        ),
    ]
