# Generated by Django 6.0.2 on 2026-02-24 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vehiculos', '0012_fichavehicular_gnc_turno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de lista')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %')),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio final')),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('forma_pago', models.CharField(choices=[('contado', 'Contado'), ('financiado', 'Financiado')], default='contado', max_length=20, verbose_name='Forma de pago')),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Anticipo')),
                ('cantidad_cuotas', models.PositiveIntegerField(default=1, verbose_name='Cantidad de cuotas')),
                ('monto_cuota', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto cuota')),
                ('interes_descripcion', models.CharField(blank=True, max_length=255, verbose_name='Interés / Descripción')),
                ('toma_usado', models.BooleanField(default=False, verbose_name='¿Toma usado?')),
                ('usado_descripcion', models.CharField(blank=True, max_length=255, verbose_name='Usado (descripción)')),
                ('usado_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor del usado')),
                ('gastos_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos transferencia')),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros gastos')),
                ('gastos_descripcion', models.CharField(blank=True, max_length=255, verbose_name='Detalle otros gastos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('validez_dias', models.PositiveIntegerField(default=7, verbose_name='Validez (días)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='borrador', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='clientes.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='vehiculos.vehiculo')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
