# Generated by Django 4.2.27 on 2026-01-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('al_dia', 'Al día'), ('deuda', 'Con deuda'), ('cerrada', 'Cerrada')], default='al_dia', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_corrientes', to='clientes.cliente')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_corriente', to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque')], max_length=20)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('numero_cheque', models.CharField(blank=True, max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cuentas.cuentacorriente')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_inicio', models.DateField()),
                ('monto_financiado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipo_plan', models.CharField(choices=[('cuotas', 'Cuotas'), ('unico', 'Pago único'), ('cheques', 'Cheques')], default='cuotas', max_length=20)),
                ('interes_descripcion', models.TextField(blank=True)),
                ('interes_mora_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos'), ('USD', 'Dólares')], default='ARS', max_length=3)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pago', to='cuentas.cuentacorriente')),
            ],
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cuentas.cuotaplan')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cuentas.pago')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('debe', 'Debe'), ('haber', 'Haber'), ('deuda', 'Deuda'), ('pago', 'Pago')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('gestoria', 'Gestoría'), ('permuta', 'Permuta'), ('ajuste', 'Ajuste'), ('venta', 'Venta')], default='manual', max_length=20)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cuentas.cuentacorriente')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_cuenta', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='cuotaplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='cuentas.planpago'),
        ),
        migrations.CreateModel(
            name='BitacoraCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='cuentas.cuentacorriente')),
            ],
        ),
    ]
