# Generated by Django 5.2.10 on 2026-01-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_pago_saldo_anterior_pago_saldo_posterior'),
        ('vehiculos', '0011_alter_fichavehicular_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoGastoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_gastos_ingreso_cc', to='vehiculos.vehiculo')),
            ],
            options={
                'ordering': ['fecha_pago'],
            },
        ),
    ]
