# Generated by Django 5.2.10 on 2026-01-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_pagogastoingreso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoGastoIngreso',
        ),
    ]
