# Generated by Django 6.0.2 on 2026-03-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_delete_pagogastoingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpago',
            name='interes_financiacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de interés aplicado al monto financiado. Ej: 40 = 40%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='interes_mora_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de mora mensual por cuota vencida. Ej: 4 = 4%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='tipo_plan',
            field=models.CharField(choices=[('cuotas', 'Cuotas en pesos'), ('unico', 'Pago único'), ('cheques', 'Cheques')], default='cuotas', max_length=20),
        ),
    ]
