# Generated by Django 6.0.2 on 2026-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_planpago_interes_financiacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], max_length=20),
        ),
    ]
