# Generated by Django 6.0.2 on 2026-04-07 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_alter_pago_forma_pago'),
        ('ventas', '0003_alter_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorriente',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_corriente', to='ventas.venta'),
        ),
    ]
