# Generated by Django 5.2.10 on 2026-05-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_plan_cuotificacion_cuota_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpago',
            name='interes_financiacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Porcentaje de interés aplicado al monto financiado. Ej: 40 = 40%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='interes_mora_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Porcentaje de mora mensual por cuota vencida (opcional). Ej: 4 = 4%', max_digits=5),
        ),
    ]
