# Generated by Django 5.2.10 on 2026-05-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
        ('cuentas', '0011_alter_planpago_interes_financiacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cheque_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_origen', to='cheques.cheque'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_cobro_cheque',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='titular_cheque',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
