# Generated by Django 5.2.10 on 2026-06-03 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_pago_cheque_vinculado_pago_fecha_cobro_cheque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpago',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='cuentas.cuentacorriente'),
        ),
    ]
