# Generated by Django 5.2.10 on 2026-06-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0013_alter_planpago_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacorriente',
            name='doc_entregada',
            field=models.BooleanField(default=False, verbose_name='Documentación vehicular entregada'),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='doc_fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega de documentación'),
        ),
        migrations.AddField(
            model_name='cuentacorriente',
            name='doc_recibo',
            field=models.FileField(blank=True, null=True, upload_to='cuentas/recibos_documentacion/', verbose_name='Recibo de entrega de documentación'),
        ),
    ]
