# Generated by Django 5.2.10 on 2026-06-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0014_cuentacorriente_doc_entregada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpago',
            name='cuota_extra_fecha',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de la cuota extra. Si se deja vacía, se usa el mes siguiente a la última cuota.', null=True, verbose_name='Vencimiento de la cuota extra'),
        ),
    ]
