# Generated by Django 5.2.10 on 2026-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0015_planpago_cuota_extra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('mixto', 'Mixto (efectivo + cheques)')], max_length=20),
        ),
    ]
