# Generated by Django 5.2.10 on 2026-07-28 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0016_alter_pago_forma_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refinanciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('base_modo', models.CharField(default='plan', max_length=10)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interes_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_refin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad_cuotas', models.PositiveIntegerField(default=1)),
                ('cuotas_previas', models.JSONField(default=list)),
                ('cuotas_nuevas', models.JSONField(default=list)),
                ('movimientos', models.JSONField(default=list)),
                ('nota', models.TextField(blank=True)),
                ('revertida', models.BooleanField(default=False)),
                ('fecha_reversion', models.DateTimeField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinanciaciones', to='cuentas.cuentacorriente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinanciaciones', to='cuentas.planpago')),
            ],
            options={
                'verbose_name': 'Refinanciación',
                'verbose_name_plural': 'Refinanciaciones',
                'ordering': ['-creada', '-id'],
            },
        ),
    ]
