# Generated by Django 4.2.27 on 2026-01-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('dominio', models.CharField(max_length=10, unique=True)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('kilometros', models.PositiveIntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('stock', 'En stock'), ('temporal', 'Temporalmente no disponible'), ('vendido', 'Vendido')], default='stock', max_length=20)),
                ('es_0km', models.BooleanField(default=False, help_text='Indica si el vehículo es 0 km')),
                ('numero_carpeta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='FichaVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_motor', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inscripcion_inicial', models.DateField(blank=True, null=True)),
                ('motor', models.CharField(blank=True, max_length=100, null=True)),
                ('chasis', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('combustible', models.CharField(blank=True, max_length=50, null=True)),
                ('transmision', models.CharField(blank=True, max_length=50, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('email_contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('titular', models.CharField(blank=True, max_length=200, null=True)),
                ('domicilio_titular', models.CharField(blank=True, max_length=200, null=True)),
                ('dni_titular', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('cuit_cuil_dni', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_ingreso', models.CharField(blank=True, choices=[('compra', 'Compra'), ('consignacion', 'Consignación')], max_length=50, null=True)),
                ('numero_consignacion_factura', models.CharField(blank=True, max_length=200, null=True)),
                ('patentes_estado', models.CharField(blank=True, choices=[('tiene', 'Tiene'), ('no_tiene', 'No tiene')], max_length=20, null=True)),
                ('patentes_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('patentes_vto1', models.DateField(blank=True, null=True)),
                ('patentes_vto2', models.DateField(blank=True, null=True)),
                ('patentes_vto3', models.DateField(blank=True, null=True)),
                ('patentes_vto4', models.DateField(blank=True, null=True)),
                ('patentes_vto5', models.DateField(blank=True, null=True)),
                ('f08_estado', models.CharField(blank=True, choices=[('tiene', 'Tiene'), ('no_tiene', 'No tiene')], max_length=20, null=True)),
                ('cedula_estado', models.CharField(blank=True, choices=[('tiene', 'Tiene'), ('no_tiene', 'No tiene')], max_length=20, null=True)),
                ('verificacion_estado', models.CharField(blank=True, choices=[('tiene', 'Tiene'), ('no_tiene', 'No tiene')], max_length=20, null=True)),
                ('verificacion_vencimiento', models.DateField(blank=True, null=True)),
                ('autopartes_estado', models.CharField(blank=True, choices=[('tiene', 'Tiene'), ('no_tiene', 'No tiene')], max_length=20, null=True)),
                ('autopartes_turno', models.DateField(blank=True, null=True)),
                ('vtv_estado', models.CharField(blank=True, choices=[('tiene', 'Tiene'), ('no_tiene', 'No tiene')], max_length=20, null=True)),
                ('vtv_turno', models.DateField(blank=True, null=True)),
                ('vtv_vencimiento', models.DateField(blank=True, null=True)),
                ('gasto_f08', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gasto_informes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gasto_patentes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gasto_verificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gasto_autopartes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gasto_vtv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gasto_r541', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gasto_firmas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('duplicado_llave_estado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('duplicado_llave_obs', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_llave_estado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('codigo_llave_obs', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_radio_estado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('codigo_radio_obs', models.CharField(blank=True, max_length=200, null=True)),
                ('manuales_estado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('manuales_obs', models.CharField(blank=True, max_length=200, null=True)),
                ('oblea_gnc_estado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('oblea_gnc_obs', models.CharField(blank=True, max_length=200, null=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='vehiculos.vehiculo')),
            ],
        ),
    ]
