# Generated by Django 4.2.27 on 2026-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_pagogastoingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='autopartes_turno_obs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones turno grabado autopartes'),
        ),
    ]
