# Generated by Django 4.2.27 on 2026-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_fichavehicular_autopartes_turno_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='cedula_check_estado',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='cedula_check_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='prenda_estado',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='prenda_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='titulo_estado',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='titulo_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fichavehicular',
            name='autopartes_turno_obs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagogastoingreso',
            name='concepto',
            field=models.CharField(max_length=100),
        ),
    ]
