# Generated by Django 5.2.10 on 2026-01-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_fichavehicular_cedula_check_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGastosIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_f08', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_informes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_patentes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_verificacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_autopartes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_vtv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_r541', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_firmas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
