# Generated by Django 5.2.10 on 2026-01-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_configuraciongastosingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='gasto_infracciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
