# Generated by Django 5.2.10 on 2026-01-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_fichavehicular_gasto_infracciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongastosingreso',
            name='gasto_infracciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
