# Generated by Django 5.2.10 on 2026-01-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_configuraciongastosingreso_gasto_infracciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='unidad',
            field=models.CharField(choices=[('HA', 'Hamichetti'), ('VA', 'Vamichetti')], default='HA', max_length=2, verbose_name='Unidad'),
        ),
    ]
