# Generated by Django 5.2.10 on 2026-01-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_vehiculo_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichavehicular',
            name='chasis',
        ),
        migrations.RemoveField(
            model_name='fichavehicular',
            name='fecha_inscripcion_inicial',
        ),
        migrations.RemoveField(
            model_name='fichavehicular',
            name='motor',
        ),
        migrations.AlterField(
            model_name='fichavehicular',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichavehicular',
            name='cuit_cuil_dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichavehicular',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fichavehicular',
            name='tipo_ingreso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichavehicular',
            name='titular',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fichavehicular',
            name='vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
