# Generated by Django 5.2.10 on 2026-01-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_remove_fichavehicular_chasis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='fecha_inscripcion_inicial',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inscripción inicial'),
        ),
    ]
