# Generated by Django 5.2.10 on 2026-01-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0003_alter_proveedor_cuit'),
        ('vehiculos', '0010_fichavehicular_fecha_inscripcion_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichavehicular',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='compraventa.proveedor', verbose_name='Agencia / Vendedor'),
        ),
    ]
