# Generated by Django 5.2.10 on 2026-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0011_alter_fichavehicular_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='gnc_turno',
            field=models.DateField(blank=True, null=True, verbose_name='Turno GNC'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='verificacion_turno',
            field=models.DateField(blank=True, null=True, verbose_name='Turno verificación policial'),
        ),
        migrations.AlterField(
            model_name='fichavehicular',
            name='tipo_ingreso',
            field=models.CharField(blank=True, choices=[('compra', 'Compra'), ('consignacion', 'Consignación')], max_length=50, null=True),
        ),
    ]
