# Generated by Django 6.0.2 on 2026-04-07 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0012_fichavehicular_gnc_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_cerrajeria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cerrajeria'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_chapa_pintura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chapa y pintura'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_gnc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='GNC'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_grabado_autopartes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Grabado autopartes'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_lavado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lavado / Pulido'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_mecanica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mecanica'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_neumaticos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neumaticos'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_otros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_tapizado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tapizado'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_verificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Verificacion policial'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_vidrios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vidrios'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_vtv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='VTV'),
        ),
        migrations.CreateModel(
            name='GastoConcesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_concesionario', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Gasto de concesionario',
                'verbose_name_plural': 'Gastos de concesionario',
                'ordering': ['fecha'],
            },
        ),
    ]
