# Generated by Django 6.0.2 on 2026-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0013_fichavehicular_gc_cerrajeria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_patentes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Patentes'),
        ),
    ]
