# Generated by Django 6.0.2 on 2026-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0014_fichavehicular_gc_patentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('stock', 'En stock'), ('temporal', 'Temporalmente no disponible'), ('vendido', 'Vendido'), ('reventa', 'En reventa')], default='stock', max_length=20),
        ),
    ]
