# Generated by Django 6.0.2 on 2026-04-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0015_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de vehículo')),
                ('potencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Potencia (HP)')),
                ('cilindrada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cilindrada')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
                ('capacidad_tanque', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tanque de combustible (L)')),
                ('capacidad_baul', models.CharField(blank=True, max_length=30, null=True, verbose_name='Capacidad de baúl (L)')),
                ('puertas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de puertas')),
                ('largo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Largo (m)')),
                ('ancho', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ancho (m)')),
                ('alto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alto (m)')),
                ('peso', models.CharField(blank=True, max_length=30, null=True, verbose_name='Peso (kg)')),
                ('abs_frenos', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='ABS')),
                ('airbag', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Airbag')),
                ('airbags_laterales', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Airbags laterales')),
                ('aire_acondicionado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Aire acondicionado')),
                ('cierre_centralizado', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Cierre centralizado')),
                ('alzacristales', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Alzacristales eléctricos')),
                ('alarma', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Alarma')),
                ('sensor_estacionamiento', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Sensor de estacionamiento')),
                ('camara_retroceso', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Cámara de retroceso')),
                ('pantalla', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Pantalla / Multimedia')),
                ('gps', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='GPS')),
                ('isofix', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='ISOFIX')),
                ('techo_solar', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Techo solar / panorámico')),
                ('llantas_aleacion', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Llantas de aleación')),
                ('control_crucero', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Control crucero')),
                ('control_traccion', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Control de tracción')),
                ('asientos_cuero', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Asientos de cuero')),
                ('bluetooth', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='Bluetooth')),
                ('est_neumaticos', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Neumáticos')),
                ('est_frenos', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Frenos')),
                ('est_amortiguadores', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Amortiguadores')),
                ('est_bateria', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Batería')),
                ('est_escape', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Escape / Silenciador')),
                ('est_chapa_pintura', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Chapa y pintura')),
                ('est_tapizado', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Tapizado')),
                ('est_vidrios', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Vidrios / Cristales')),
                ('est_luces', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Luces')),
                ('est_motor', models.CharField(blank=True, choices=[('ok', 'OK'), ('regular', 'Regular'), ('malo', 'Malo'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Motor')),
                ('observaciones_tecnicas', models.TextField(blank=True, null=True, verbose_name='Observaciones técnicas')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Ficha técnica',
                'verbose_name_plural': 'Fichas técnicas',
            },
        ),
    ]
