# Generated by Django 5.2.10 on 2026-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0017_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='largo',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='peso',
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='chocado',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('leve', 'Leve'), ('importante', 'Importante')], max_length=15, null=True, verbose_name='¿Tuvo choque?'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='detalles_choque',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles del choque'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='detalles_estado',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles (rayones, golpes, particularidades)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='no_funciona',
            field=models.TextField(blank=True, null=True, verbose_name='¿Algo no funciona?'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='partes_repintadas',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Partes repintadas'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='repintado',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('parcial', 'Parcial'), ('si', 'Sí, completo')], max_length=10, null=True, verbose_name='¿Repintado?'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='ultimo_cambio_aceite_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Cambio de aceite – Fecha'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='ultimo_cambio_aceite_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cambio de aceite – Km'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='ultimo_cambio_correa_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Cambio de correa – Fecha'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='ultimo_cambio_correa_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cambio de correa – Km'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='ultimo_service_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Último service – Fecha'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='ultimo_service_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Último service – Km'),
        ),
    ]
