# Generated by Django 5.2.10 on 2026-05-30 12:50

from django.db import migrations, models


def _migrar_f08_tiene(apps, schema_editor):
    """Mapea registros viejos con f08_estado='tiene' al nuevo origen 'concesionario'."""
    FichaVehicular = apps.get_model('vehiculos', 'FichaVehicular')
    FichaVehicular.objects.filter(f08_estado='tiene').update(f08_estado='concesionario')


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0018_remove_fichatecnica_alto_remove_fichatecnica_ancho_and_more'),
    ]

    operations = [
        migrations.RunPython(_migrar_f08_tiene, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fichavehicular',
            name='f08_estado',
            field=models.CharField(blank=True, choices=[('concesionario', 'Concesionario'), ('proveedor', 'Proveedor'), ('reventa', 'Reventa'), ('no_tiene', 'No tiene')], max_length=20, null=True, verbose_name='Formulario 08 (origen)'),
        ),
    ]
