# Generated by Django 5.2.10 on 2026-05-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0019_alter_fichavehicular_f08_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='informe',
            field=models.CharField(blank=True, choices=[('prendado', 'Prendado'), ('sucesion', 'Sucesión'), ('inhibido', 'Inhibido'), ('embargado', 'Embargado')], max_length=20, null=True, verbose_name='Informe'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='radicacion_anterior',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Radicación anterior'),
        ),
    ]
