# Generated by Django 5.2.10 on 2026-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0021_sync_vendedor_ficha_a_compraventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='abs_frenos',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='airbag',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='airbags_laterales',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='aire_acondicionado',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='alarma',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='alzacristales',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='asientos_cuero',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='camara_retroceso',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='capacidad_baul',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='capacidad_tanque',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='cierre_centralizado',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='cilindrada',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='control_crucero',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='control_traccion',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_amortiguadores',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_bateria',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_chapa_pintura',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_escape',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_frenos',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_luces',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_motor',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_neumaticos',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_tapizado',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='est_vidrios',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='isofix',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='llantas_aleacion',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='pantalla',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='potencia',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='puertas',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='sensor_estacionamiento',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='techo_solar',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='tipo_vehiculo',
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='cubierta_auxilio',
            field=models.CharField(blank=True, choices=[('nueva', 'Nueva'), ('buena', 'Buena'), ('regular', 'Regular'), ('desgastada', 'Desgastada'), ('cambiar', 'A cambiar')], max_length=15, null=True, verbose_name='Rueda de auxilio'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='cubierta_dd',
            field=models.CharField(blank=True, choices=[('nueva', 'Nueva'), ('buena', 'Buena'), ('regular', 'Regular'), ('desgastada', 'Desgastada'), ('cambiar', 'A cambiar')], max_length=15, null=True, verbose_name='Cubierta delantera der.'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='cubierta_di',
            field=models.CharField(blank=True, choices=[('nueva', 'Nueva'), ('buena', 'Buena'), ('regular', 'Regular'), ('desgastada', 'Desgastada'), ('cambiar', 'A cambiar')], max_length=15, null=True, verbose_name='Cubierta delantera izq.'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='cubierta_td',
            field=models.CharField(blank=True, choices=[('nueva', 'Nueva'), ('buena', 'Buena'), ('regular', 'Regular'), ('desgastada', 'Desgastada'), ('cambiar', 'A cambiar')], max_length=15, null=True, verbose_name='Cubierta trasera der.'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='cubierta_ti',
            field=models.CharField(blank=True, choices=[('nueva', 'Nueva'), ('buena', 'Buena'), ('regular', 'Regular'), ('desgastada', 'Desgastada'), ('cambiar', 'A cambiar')], max_length=15, null=True, verbose_name='Cubierta trasera izq.'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='cubiertas_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones cubiertas / auxilio'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_aire',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Aire acondicionado'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_calefaccion',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Calefacción'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_electrico',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Sistema eléctrico'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_faros_opticas',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Faros y ópticas'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_frenos',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Sistema de frenos'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_motor',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Estado del motor'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_suspension',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Suspensión'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_tapizados',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Tapizados'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_vidrios',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Vidrios'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='estado_volante',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('no_funciona', 'No funciona')], max_length=15, null=True, verbose_name='Desgaste del volante'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='fallas_electrico_obs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalle de fallas eléctricas'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='granizo_estado',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo')], max_length=15, null=True, verbose_name='Granizo'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='granizo_obs',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles del granizo (zonas afectadas)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='perdida_fluidos',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('leve', 'Leve'), ('importante', 'Importante')], max_length=15, null=True, verbose_name='Pérdida de fluidos'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='perdida_fluidos_obs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalle pérdida de fluidos'),
        ),
    ]
