# Generated by Django 5.2.10 on 2026-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0022_remove_fichatecnica_abs_frenos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='dominio',
            field=models.CharField(max_length=15),
        ),
    ]
