# Generated by Django 5.2.10 on 2026-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0023_alter_vehiculo_dominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagogastoingreso',
            name='mantiene_deuda_vehiculo',
            field=models.BooleanField(default=False, verbose_name='Sigue como deuda del vehículo (no se pagó al ente)'),
        ),
    ]
