# Generated by Django 5.2.10 on 2026-06-09 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0024_pagogastoingreso_mantiene_deuda_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today, help_text='Fecha en que el vehículo ingresó al stock. Se completa automáticamente con la fecha de alta y se puede editar.', verbose_name='Fecha de ingreso'),
        ),
    ]
