# Generated by Django 5.2.10 on 2026-06-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0025_vehiculo_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='patente_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto de la patente mensual'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='patentes_adeuda',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True, verbose_name='¿Adeuda patentes a la fecha de ingreso?'),
        ),
        migrations.AlterField(
            model_name='fichavehicular',
            name='patentes_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto adeudado de patentes'),
        ),
    ]
