# Generated by Django 5.2.10 on 2026-06-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0026_fichavehicular_patente_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagogastoingreso',
            name='ente',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pagogastoingreso',
            name='fecha_saldado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagogastoingreso',
            name='movimiento_cuenta_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagogastoingreso',
            name='pago_futuro_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagogastoingreso',
            name='pertenece',
            field=models.CharField(choices=[('proveedor', 'Proveedor'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
        migrations.AddField(
            model_name='pagogastoingreso',
            name='reintegro_proveedor_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagogastoingreso',
            name='saldado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagogastoingreso',
            name='situacion',
            field=models.CharField(choices=[('prov_directo', 'Proveedor pagó directo al ente (saldado)'), ('prov_reintegro', 'Lo pagué yo, el proveedor me reintegra'), ('cli_directo', 'Cliente pagó directo al ente (saldado)'), ('cli_concesion', 'Cliente me pagó, todavía no pagué al ente'), ('cli_adelanto', 'Adelanté yo al ente, el cliente me debe'), ('pendiente', 'Nadie pagó todavía')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagogastoingreso',
            name='mantiene_deuda_vehiculo',
            field=models.BooleanField(default=False, verbose_name='(legado) Sigue como deuda del vehículo'),
        ),
    ]
