# Generated by Django 5.2.10 on 2026-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0028_poblar_situacion_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagogastoingreso',
            name='situacion',
            field=models.CharField(choices=[('prov_directo', 'Proveedor pagó directo al organismo (saldado)'), ('prov_reintegro', 'Lo pagué yo, el proveedor me reintegra'), ('cli_directo', 'Cliente pagó directo al organismo (saldado)'), ('cli_concesion', 'Cliente me pagó, todavía no pagué al organismo'), ('cli_adelanto', 'Adelanté yo al organismo, el cliente me debe'), ('pendiente', 'Nadie pagó todavía')], default='pendiente', max_length=20),
        ),
    ]
