# Generated by Django 5.2.10 on 2026-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0029_alter_pagogastoingreso_situacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('a_ingresar', 'A ingresar'), ('stock', 'En stock'), ('temporal', 'Temporalmente no disponible'), ('vendido', 'Vendido'), ('reventa', 'En reventa')], default='stock', max_length=20),
        ),
    ]
