# Generated by Django 5.2.10 on 2026-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0031_limpiar_gc_autocopias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('a_ingresar', 'A ingresar'), ('stock', 'En stock'), ('temporal', 'No disponible'), ('vendido', 'Vendido'), ('reventa', 'En reventa')], default='stock', max_length=20),
        ),
    ]
