# Generated by Django 5.2.10 on 2026-06-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0032_alter_vehiculo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='titulo_archivo',
            field=models.FileField(blank=True, null=True, upload_to='titulos/'),
        ),
    ]
