# Generated by Django 5.2.10 on 2026-06-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0033_fichavehicular_titulo_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoGastoConcesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ente', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_gastos_concesionario', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Pago de gasto de concesionario',
                'verbose_name_plural': 'Pagos de gastos de concesionario',
                'ordering': ['-fecha_pago', '-creado'],
            },
        ),
    ]
