# Generated by Django 5.2.10 on 2026-06-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0034_pagogastoconcesionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichavehicular',
            name='f08_estado',
            field=models.CharField(blank=True, choices=[('concesionario', 'Concesionario'), ('proveedor', 'Proveedor'), ('reventa', 'Reventa'), ('en_proceso', 'En proceso'), ('no_tiene', 'No tiene')], max_length=20, null=True, verbose_name='Formulario 08 (origen)'),
        ),
    ]
