# Generated by Django 5.2.10 on 2026-06-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0035_alter_fichavehicular_f08_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='precio_reventa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de reventa'),
        ),
    ]
