# Generated by Django 5.2.10 on 2026-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0036_vehiculo_precio_reventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='gc_patentes_manual',
            field=models.BooleanField(default=False),
        ),
    ]
