# Generated by Django 5.2.10 on 2026-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0037_fichavehicular_gc_patentes_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='visita_pendiente',
            field=models.BooleanField(default=False, verbose_name='Van a venir a verlo'),
        ),
    ]
