# Generated by Django 5.2.10 on 2026-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0038_vehiculo_visita_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='fecha_inscripcion_habitualista',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inscripción a nombre del comerciante habitualista'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='es_habitualista',
            field=models.BooleanField(default=False, help_text='Marcá si el vehículo ingresó con beneficio de comerciante habitualista.', verbose_name='Comerciante habitualista'),
        ),
    ]
