# Generated by Django 5.2.10 on 2026-07-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0039_fichavehicular_fecha_inscripcion_habitualista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='cedula_archivo',
            field=models.FileField(blank=True, null=True, upload_to='cedulas/'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='infracciones_archivo',
            field=models.FileField(blank=True, null=True, upload_to='deudas/', verbose_name='Comprobante de deuda de infracciones'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='patentes_archivo',
            field=models.FileField(blank=True, null=True, upload_to='deudas/', verbose_name='Comprobante de deuda de patentes'),
        ),
    ]
