# Generated by Django 5.2.10 on 2026-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0040_fichavehicular_cedula_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichavehicular',
            name='costo_verificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de verificación'),
        ),
        migrations.AddField(
            model_name='fichavehicular',
            name='costo_vtv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de VTV'),
        ),
    ]
