# Generated by Django 4.2.27 on 2026-01-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteanual',
            options={'ordering': ['-anio'], 'verbose_name': 'Reporte Anual', 'verbose_name_plural': 'Reportes Anuales'},
        ),
        migrations.AlterModelOptions(
            name='reportemensual',
            options={'ordering': ['-anio', '-mes'], 'verbose_name': 'Reporte Mensual', 'verbose_name_plural': 'Reportes Mensuales'},
        ),
        migrations.AlterField(
            model_name='reporteanual',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se realizó el cierre anual'),
        ),
        migrations.AlterField(
            model_name='reportemensual',
            name='fecha_cierre',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se realizó el cierre mensual'),
        ),
        migrations.CreateModel(
            name='FichaReporteInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de compra')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio de compra')),
                ('fecha_venta', models.DateField(blank=True, null=True, verbose_name='Fecha de venta')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio de venta')),
                ('comprador', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comprador')),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total de gastos')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_reporte', to='vehiculos.vehiculo')),
            ],
        ),
    ]
