# Generated by Django 4.2.27 on 2026-01-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_reporteanual_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichareporteinterno',
            name='total_gastos',
        ),
        migrations.CreateModel(
            name='GastoReporteInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='reportes.fichareporteinterno')),
            ],
        ),
    ]
