# Generated by Django 4.2.27 on 2026-01-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_remove_fichareporteinterno_total_gastos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteanual',
            name='ganancia_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ganancia anual'),
        ),
        migrations.AddField(
            model_name='reportemensual',
            name='ganancia_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ganancia mensual'),
        ),
    ]
