# Generated by Django 6.0.2 on 2026-04-04 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vehiculos', '0012_fichavehicular_gnc_turno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('origen', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefono', 'Teléfono'), ('presencial', 'Presencial'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('mercadolibre', 'MercadoLibre'), ('referido', 'Referido'), ('otro', 'Otro')], default='whatsapp', max_length=20)),
                ('etapa', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_negociacion', 'En negociación'), ('presupuestado', 'Presupuestado'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('vehiculo_interes_texto', models.CharField(blank=True, help_text='Si el vehículo no está en stock', max_length=200, null=True, verbose_name='Vehículo de interés (texto libre)')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_proximo_contacto', models.DateField(blank=True, null=True, verbose_name='Próximo contacto')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to='clientes.cliente', verbose_name='Cliente convertido')),
                ('vehiculo_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to='vehiculos.vehiculo', verbose_name='Vehículo de interés')),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('visita', 'Visita'), ('email', 'Email'), ('nota', 'Nota interna')], default='whatsapp', max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='crm.prospecto')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
