# Generated by Django 6.0.2 on 2026-04-06 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('vehiculos', '0012_fichavehicular_gnc_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=300)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='crm.prospecto')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_crm', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Notificacion CRM',
                'verbose_name_plural': 'Notificaciones CRM',
                'ordering': ['-fecha'],
            },
        ),
    ]
