# Generated by Django 4.2.27 on 2026-01-07 19:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('boletos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('beneficiario', models.CharField(default='AMICHETTI HUGO ALBERTO', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('lugar_emision', models.CharField(default='Rojas', max_length=100)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lugar_vencimiento', models.CharField(default='Rojas', max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagares', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
