# Generated by Django 4.2.27 on 2026-01-07 21:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('boletos', '0002_pagare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagare',
            name='lugar_vencimiento',
        ),
        migrations.CreateModel(
            name='PagareLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario', models.CharField(default='AMICHETTI HUGO ALBERTO', max_length=255)),
                ('lugar_emision', models.CharField(default='Rojas', max_length=100)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagares_lotes', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='pagare',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagares', to='boletos.pagarelote'),
        ),
    ]
