# Generated by Django 4.2.27 on 2026-01-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0003_remove_pagare_lugar_vencimiento_pagarelote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletocompraventa',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='boletos/'),
        ),
    ]
