# Generated by Django 4.2.27 on 2026-01-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0004_boletocompraventa_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagare',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pagares/'),
        ),
    ]
