# Generated by Django 5.2.10 on 2026-01-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0005_pagare_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarelote',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pagares/lotes/'),
        ),
    ]
