# Generated by Django 6.0.2 on 2026-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0006_pagarelote_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarelote',
            name='dia_vencimiento',
            field=models.PositiveIntegerField(default=10, verbose_name='Día de vencimiento mensual'),
        ),
    ]
