# Generated by Django 6.0.2 on 2026-03-20 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0007_pagarelote_dia_vencimiento'),
        ('vehiculos', '0012_fichavehicular_gnc_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_nombre', models.CharField(max_length=200, verbose_name='Apellido y Nombre / Razón Social')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('domicilio', models.CharField(max_length=300, verbose_name='Domicilio')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('cuit', models.CharField(blank=True, max_length=20, verbose_name='CUIT')),
                ('iva', models.CharField(blank=True, max_length=50, verbose_name='I.V.A.')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('anio', models.CharField(blank=True, max_length=10, verbose_name='Año')),
                ('dominio', models.CharField(blank=True, max_length=20, verbose_name='Dominio')),
                ('motor_nro', models.CharField(blank=True, max_length=100, verbose_name='Motor N°')),
                ('chasis_nro', models.CharField(blank=True, max_length=100, verbose_name='Chasis N°')),
                ('precio_vehiculo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio del Vehículo')),
                ('opcionales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Opcionales / Otros gastos')),
                ('total_a_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total a Pagar')),
                ('senia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Seña')),
                ('contado_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Contado Efectivo')),
                ('pago_entrega', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='A pagar contra entrega (efectivo)')),
                ('cheques', models.TextField(blank=True, verbose_name='Cheques (detalle)')),
                ('total_propuesta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Propuesta')),
                ('credito_prendario', models.BooleanField(default=False, verbose_name='Crédito Prendario autorizado')),
                ('otro_concepto', models.CharField(blank=True, max_length=300, verbose_name='Otro concepto')),
                ('cant_cuotas', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Cuotas')),
                ('valor_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor de Cuota')),
                ('dia_cuota', models.CharField(blank=True, max_length=10, verbose_name='Día de Vencimiento Cuota')),
                ('permuta_marca', models.CharField(blank=True, max_length=100, verbose_name='Marca (usado)')),
                ('permuta_patente', models.CharField(blank=True, max_length=20, verbose_name='Patente (usado)')),
                ('permuta_suma', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Suma propuesta (usado)')),
                ('permuta_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total con permuta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('numero_reserva', models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° Reserva')),
                ('fecha_reserva', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Reserva')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-creado'],
            },
        ),
    ]
