# Generated by Django 6.0.2 on 2026-04-07 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0008_reserva'),
        ('vehiculos', '0012_fichavehicular_gnc_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('dominio', models.CharField(max_length=20)),
                ('anio', models.CharField(blank=True, max_length=10, null=True)),
                ('motor', models.CharField(blank=True, max_length=100, null=True)),
                ('chasis', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_comprador', models.CharField(max_length=150)),
                ('dni_comprador', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio_comprador', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_comprador', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('cedula', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('cedula_azul', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('formulario_08', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('formulario_02', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('formulario_12', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('formulario_13d', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('gp01', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2, verbose_name='GP 01')),
                ('gnc', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2, verbose_name='GNC')),
                ('vtv', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2, verbose_name='VTV')),
                ('verificacion_policial', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('informe_dominio', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('infracciones', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('patentes_al_dia', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('libre_deuda', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('manuales', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('codigo_radio', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('llave_duplicado', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('rueda_auxilio', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('gato_llave_rueda', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_documentacion', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Entrega de documentacion',
                'verbose_name_plural': 'Entregas de documentacion',
                'ordering': ['-fecha'],
            },
        ),
    ]
