# Generated by Django 5.2.10 on 2026-01-27 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0007_configuraciongastosingreso_gasto_infracciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=60, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DeudaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deuda_proveedor', to='vehiculos.vehiculo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='compraventa.proveedor')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nota', models.CharField(blank=True, max_length=200, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compraventa.deudaproveedor')),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='CompraVentaOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('PROVEEDOR', 'Proveedor / Agencia'), ('CLIENTE', 'Cliente'), ('DIRECTA', 'Compra directa')], default='PROVEEDOR', max_length=20)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gastos_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PUBLICADO', 'Publicado'), ('VENDIDO', 'Vendido'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='operacion_compra', to='vehiculos.vehiculo')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Obligatorio si origen = PROVEEDOR', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='compraventa.proveedor')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
