# Generated by Django 5.2.10 on 2026-01-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagoproveedor',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre_empresa']},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(default='00-00000000-0', help_text='Formato: XX-XXXXXXXX-X', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_empresa',
            field=models.CharField(default='PROVEEDOR SIN NOMBRE', max_length=150, unique=True, verbose_name='Nombre de la empresa'),
            preserve_default=False,
        ),
    ]
