# Generated by Django 5.2.10 on 2026-01-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0002_alter_pagoproveedor_options_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(default='00-00000000-0', max_length=13, unique=True),
        ),
    ]
