# Generated by Django 5.2.10 on 2026-01-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0003_alter_proveedor_cuit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deudaproveedor',
            options={'ordering': ['-creado'], 'verbose_name': 'Deuda de proveedor', 'verbose_name_plural': 'Deudas de proveedores'},
        ),
    ]
