# Generated by Django 5.2.10 on 2026-01-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0004_alter_deudaproveedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraventaoperacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Obligatorio si origen = PROVEEDOR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='compraventa.proveedor'),
        ),
        migrations.AlterField(
            model_name='deudaproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='compraventa.proveedor'),
        ),
    ]
