# Generated by Django 6.0.2 on 2026-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0005_alter_compraventaoperacion_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='alias_bancario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cbu',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='CBU'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular de la cuenta'),
        ),
    ]
