# Generated by Django 5.2.10 on 2026-06-10 01:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0006_proveedor_alias_bancario_proveedor_banco_and_more'),
        ('vehiculos', '0027_pagogastoingreso_ente_pagogastoingreso_fecha_saldado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReintegroProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('ente', models.CharField(blank=True, max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de reintegro'), ('reintegrado', 'Reintegrado')], default='pendiente', max_length=12)),
                ('fecha_reintegro', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reintegros_gastos', to='compraventa.proveedor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reintegros_proveedor', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Reintegro de proveedor',
                'verbose_name_plural': 'Reintegros de proveedores',
                'ordering': ['-creado'],
            },
        ),
    ]
