# Generated by Django 4.2.27 on 2026-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dni_cuit', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cumplimiento_pago', models.CharField(choices=[('verde', 'Cumple en tiempo y forma'), ('amarillo', 'Atrasos moderados'), ('rojo', 'Incumplimiento')], default='verde', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReglaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_cliente', models.CharField(choices=[('verde', 'Cliente cumplidor'), ('amarillo', 'Cliente con atrasos'), ('rojo', 'Cliente incumplidor')], max_length=10, unique=True)),
                ('permite_financiacion', models.BooleanField(default=True)),
                ('anticipo_minimo_porcentaje', models.PositiveIntegerField(help_text='Porcentaje mínimo de anticipo requerido')),
                ('max_cuotas', models.PositiveIntegerField(help_text='Cantidad máxima de cuotas permitidas')),
                ('acepta_cheques', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
