# Generated by Django 6.0.2 on 2026-02-25 13:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('nro_factura', models.CharField(blank=True, max_length=50, verbose_name='Nro de Factura')),
                ('banco_emision', models.CharField(max_length=100, verbose_name='Banco de emisión')),
                ('numero_cheque', models.CharField(max_length=50, verbose_name='Número de cheque')),
                ('titular_cheque', models.CharField(max_length=255, verbose_name='Titular del cheque')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha_deposito', models.DateField(verbose_name='Fecha de depósito/cobro')),
                ('estado', models.CharField(choices=[('a_depositar', 'A Depositar'), ('depositado', 'Depositado'), ('endosado', 'Endosado'), ('rechazado', 'Rechazado')], default='a_depositar', max_length=20, verbose_name='Estado')),
                ('depositado_en', models.CharField(blank=True, max_length=255, verbose_name='Depositado en')),
                ('fecha_endoso', models.DateField(blank=True, null=True, verbose_name='Fecha de endoso')),
                ('destinatario_endoso', models.CharField(blank=True, max_length=255, verbose_name='Destinatario del endoso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['fecha_deposito', '-monto'],
            },
        ),
    ]
