# Generated by Django 6.0.2 on 2026-02-24 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recibido', 'Recibido'), ('emitido', 'Emitido')], max_length=20, verbose_name='Tipo')),
                ('numero', models.CharField(max_length=50, verbose_name='Número de cheque')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('titular', models.CharField(max_length=255, verbose_name='Titular')),
                ('cuit_titular', models.CharField(blank=True, max_length=20, verbose_name='CUIT Titular')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_cobro', models.DateField(verbose_name='Fecha de cobro')),
                ('estado', models.CharField(choices=[('cartera', 'En cartera'), ('depositado', 'Depositado'), ('cobrado', 'Cobrado'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='cartera', max_length=20, verbose_name='Estado')),
                ('origen_destino', models.CharField(help_text='De quién se recibió o a quién se entregó', max_length=255, verbose_name='Origen/Destino')),
                ('concepto', models.CharField(blank=True, max_length=255, verbose_name='Concepto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['-fecha_cobro'],
            },
        ),
    ]
