# Generated by Django 5.2.10 on 2026-06-10 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
        ('cuentas', '0014_cuentacorriente_doc_entregada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_cobro', to='cuentas.pago', verbose_name='Cobro que saldó'),
        ),
        migrations.CreateModel(
            name='MovimientoCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_nuevo', models.CharField(choices=[('a_depositar', 'A Depositar'), ('depositado', 'Depositado'), ('endosado', 'Endosado'), ('rechazado', 'Rechazado')], max_length=20)),
                ('destinatario', models.CharField(blank=True, max_length=255, verbose_name='Destinatario (endoso)')),
                ('detalle', models.CharField(blank=True, max_length=255, verbose_name='Detalle')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cheques.cheque')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de cheque',
                'verbose_name_plural': 'Movimientos de cheques',
                'ordering': ['-fecha'],
            },
        ),
    ]
