# Generated by Django 5.2.10 on 2026-05-26 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=200, verbose_name='Servicio / Sitio')),
                ('usuario', models.CharField(blank=True, max_length=200, verbose_name='Usuario / Email')),
                ('contrasena', models.CharField(max_length=300, verbose_name='Contraseña')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contraseña',
                'verbose_name_plural': 'Contraseñas',
                'ordering': ['servicio'],
            },
        ),
    ]
