# Generated by Django 5.2.10 on 2026-06-01 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_internas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Local centro, Galpón, Depósito anexo', max_length=255, verbose_name='Nombre / Inmueble')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('propietario', models.CharField(blank=True, max_length=255, verbose_name='Propietario')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('monto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto mensual')),
                ('dia_pago', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes en que se paga (1-31)', null=True, verbose_name='Día de pago')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Inicio de contrato')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fin de contrato')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PagoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de pago')),
                ('periodo', models.CharField(blank=True, help_text='Ej: Junio 2026', max_length=50, verbose_name='Período')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='transferencia', max_length=20, verbose_name='Forma de pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cuentas_internas.alquiler')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de alquiler',
                'verbose_name_plural': 'Pagos de alquiler',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
