# Generated by Django 5.2.10 on 2026-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_internas', '0002_alquiler_pagoalquiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='pagoalquiler',
            name='periodo',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='arrendatario',
            field=models.CharField(blank=True, help_text='Quién alquila y paga el alquiler', max_length=255, verbose_name='Arrendatario / Inquilino'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='contrato',
            field=models.FileField(blank=True, help_text='PDF o imagen del contrato firmado', null=True, upload_to='alquileres/contratos/', verbose_name='Contrato escaneado'),
        ),
        migrations.AddField(
            model_name='pagoalquiler',
            name='periodo_anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año del período'),
        ),
        migrations.AddField(
            model_name='pagoalquiler',
            name='periodo_mes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes del período'),
        ),
        migrations.AlterField(
            model_name='pagoalquiler',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de cobro'),
        ),
    ]
