# Generated by Django 5.2.10 on 2026-06-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_internas', '0003_remove_alquiler_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='aumento_cada_meses',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cada cuántos meses aumenta. Ej: 3 = trimestral. Vacío = sin aumento.', null=True, verbose_name='Aumenta cada (meses)'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='aumento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Porcentaje de aumento. Ej: 10 = 10%', max_digits=6, verbose_name='Aumento (%)'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='monto_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto inicial. Si hay aumento programado, se ajusta solo.', max_digits=12, verbose_name='Monto mensual'),
        ),
    ]
