# Generated by Django 5.2.10 on 2026-06-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_internas', '0004_alquiler_aumento_cada_meses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='aumento_cada_meses',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='aumento_porcentaje',
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='monto_mensual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto inicial. Podés cargar aumentos por tramo más abajo.', max_digits=12, verbose_name='Monto mensual'),
        ),
        migrations.CreateModel(
            name='EscalaAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(verbose_name='Vigente desde')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('observaciones', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='cuentas_internas.alquiler')),
            ],
            options={
                'verbose_name': 'Tramo de monto',
                'verbose_name_plural': 'Tramos de monto',
                'ordering': ['vigente_desde'],
            },
        ),
    ]
