# Generated by Django 5.2.10 on 2026-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0003_separar_alquileres'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisousuario',
            name='ver_precio',
            field=models.BooleanField(default=True, verbose_name='Puede ver precios'),
        ),
    ]
